// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "protocol/zigbee/app/framework/util/tokens.h"

// Custom token header file
#include "app/builder/Z3Aliyun3011/Z3Aliyun_custom_tokens.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

